# Generated by Django 4.2 on 2023-11-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("adopted", "Adopted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="static/images/default_pet_image.png",
                        null=True,
                        upload_to="pets/",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                (
                    "size",
                    models.CharField(
                        choices=[("1", "small"), ("2", "medium"), ("3", "large")],
                        max_length=100,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("behavior", models.TextField(blank=True, null=True)),
                ("addition", models.TextField(blank=True, null=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
